### DISCUSSION TITLE
Plex Error - Couldn't Reach Local Server

### DISCUSSION THREAD

**Discussion by townsmcp** [I-am-PUID-0/pdrcrd#23] [General]
**Describe the bug**

I have gone through the config, entering all correct values (my Plex container is accessible on http://192.168.1.233:32400.
After installing pdrcrd and it starting, the logs shows an error and the container just sits waiting:

[12/12/23 09:45:59] [plex error]: couldnt reach local plex server at: http://192.168.1.233:32400 to determine library sections. Make sure the address is correct, the server is running, and youve set up at least one library.
[12/12/23 09:45:59] [plex] getting all watchlists ... done

<img width="1124" alt="image" src="https://github.com/I-am-PUID-0/pdrcrd/assets/14061617/2a42b75c-993a-407d-a8ec-a541bc4c3efa">

**To Reproduce**

Perform install, entering Plex local IP as part of config

**Expected behavior**

plex_debrid to be able to see and talk to Plex

**Please complete the following information:**
 - OS: Ubuntu
 - Version: 22.04 LTS running in a VM inside Proxmox
 - Supporting Applications: Docker, Portainer, Plex etc

**Additional context**

I believe the issue is because docker network is set to 'compose_default' and the container cannot see anything outside of itself.
When I change the network to 'Proxy' and add a value such as 'pdrcrd' this container can then see Plex
<img width="998" alt="image" src="https://github.com/I-am-PUID-0/pdrcrd/assets/14061617/0a134b0c-1d2c-4299-9d0c-b49c83b39c77">

<img width="1124" alt="image" src="https://github.com/I-am-PUID-0/pdrcrd/assets/14061617/6788b683-c689-4111-ab82-b10e733c37ad">

Maybe as part of the config/compose add:
```
networks:
  proxy:
    driver: bridge
    external: true
```

**Comment by I-am-PUID-0** [comment]
Hi @townsmcp, 

Great write-up! I have converted this to a discussion, as the network configuration of the compose is user-based. Each user will need to define or adapt the example compose to suit their deployment. For example, my configuration uses `network_mode: container:gluetun`, as a VPN is required for my deployment due to realdebrid blocking my server's public IP address.

**Reply by townsmcp** [reply]
I have been testing the above out a bit more and updated the docker-compose.yml to include:
```
services:
  pdrcrd:
    container_name: pdrcrd
    image: iampuid0/pdrcrd:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t    
    volumes:
      - /opt/appdata/plex_db/config:/config # rclone.conf & settings.json will both be here on the host CAUTION: rclone.conf is overwritten upon start/restart of the container
      - /opt/appdata/plex_db/log:/log # logs will be here on the host
      - /opt/appdata/plex_db/rclone:/data:shared #rclone mount will be here on the host  
    environment:
      - TZ=Europe/London
      - RD_API_KEY=XXX
      - RCLONE_MOUNT_NAME=torrents
      - RCLONE_LOG_LEVEL=INFO
      - RCLONE_LOG_FILE=/log/torrents.txt
      - RCLONE_DIR_CACHE_TIME=10s #optional, but recommended as default
#      - RCLONE_CACHE_DIR=/cache #optional
#      - RCLONE_VFS_CACHE_MODE=full #optional
#      - RCLONE_VFS_CACHE_MAX_SIZE=100G #optional
#      - RCLONE_VFS_CACHE_MAX_AGE=1h #optional
#      - RCLONE_DIR_PERMS=777 #optional, not functional in beta
#      - RCLONE_FILE_PERMS=777 #optional, not functional in beta
#      - RCLONE_UMASK= #optional, not functional in beta
      - PLEX_USER=townsmcp  #required 
      - PLEX_TOKEN=XXX  #required - see link for detail https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
      - PLEX_ADDRESS=http://192.168.1.233:32400 #required - format must include http:// and have no trailing characters after 32400 e.g / 
      - SHOW_MENU=false  #optional - if used, value must be true or false -- default is true
#       - PD_LOGFILE=true  #optional - if used, value must be true or false -- default is false
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - no-new-privileges
    networks:
      - proxy
#    restart: unless-stopped
networks:
  proxy:
    driver: bridge
    external: true
```

The key additions are the 2 `networks` sections near the bottom. This seems to be working and pulling through rclone defined folder :)

I recently started looking into gluetun but needed to rebuild my media server completely :(

The one thing I'm lost with is how to interact with the container to be able to edit the plex_debrid settings - if I try to grab a console I get a 'Connection failure' message
